### PR TITLE
minor tweak to README

### PR DESCRIPTION
**Pull request by DevinNorgarb**
A useful package, accept my minor tweak to the README as a thank you.

### CODE REVIEW

**Comment by jrl05k** [comment]
spam?

**Comment by DevinNorgarb** [comment]
Genuinely found this package useful. and noticed that the line wasn't formatted correctly, so I fixed it.  

If you think this is spam please reject this PR

**Comment by jrl05k** [comment]
please explain your change

**Comment by jrl05k** [comment]
Your commit does not fix any formatting in the readme file as you said.

All you did was replace the packagist name with the name to your repository for an entirely different package. 

I can only conclude that this was spam attempt in the hopes I would commit it without reading it.

Please to do not spam this repository again.

**Pull request closed without merging**
